In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.regressionplots import influence_plot
import statsmodels.formula.api as smf
import numpy as np

In [7]:
cars = pd.read_csv('Toyoto_Corrola.csv')
cars.head()


Id                                           Model  Price  Age_08_04  \
0   1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1   2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2   3  ÊTOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3   4   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4   5     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   

      KM  HP  Doors  Cylinders  Gears  Weight  
0  46986  90      3          4      5    1165  
1  72937  90      3          4      5    1165  
2  41711  90      3          4      5    1165  
3  48000  90      3          4      5    1165  
4  38500  90      3          4      5    1170

In [8]:
cars.isna().sum()

Id           0
Model        0
Price        0
Age_08_04    0
KM           0
HP           0
Doors        0
Cylinders    0
Gears        0
Weight       0
dtype: int64

In [9]:
cars.columns

Index(['Id', 'Model', 'Price', 'Age_08_04', 'KM', 'HP', 'Doors', 'Cylinders',
       'Gears', 'Weight'],
      dtype='object')

In [12]:
cars.drop(['Id','Model'],axis=1,inplace=True)

In [13]:
cars.corr()

Price  Age_08_04        KM        HP     Doors  Cylinders  \
Price      1.000000  -0.876590 -0.569960  0.314990  0.185326        NaN   
Age_08_04 -0.876590   1.000000  0.505672 -0.156622 -0.148359        NaN   
KM        -0.569960   0.505672  1.000000 -0.333538 -0.036197        NaN   
HP         0.314990  -0.156622 -0.333538  1.000000  0.092424        NaN   
Doors      0.185326  -0.148359 -0.036197  0.092424  1.000000        NaN   
Cylinders       NaN        NaN       NaN       NaN       NaN        NaN   
Gears      0.063104  -0.005364  0.015023  0.209477 -0.160141        NaN   
Weight     0.581198  -0.470253 -0.028598  0.089614  0.302618        NaN   

              Gears    Weight  
Price      0.063104  0.581198  
Age_08_04 -0.005364 -0.470253  
KM         0.015023 -0.028598  
HP         0.209477  0.089614  
Doors     -0.160141  0.302618  
Cylinders       NaN       NaN  
Gears      1.000000  0.020613  
Weight     0.020613  1.000000

In [14]:
import statsmodels.formula.api as smf 
model = smf.ols('Price~Age_08_04+KM+HP+Doors+Gears+Weight',data=cars).fit()

In [15]:
model.params

Intercept   -6984.373566
Age_08_04    -122.242218
KM             -0.019994
HP             28.350149
Doors          -9.680229
Gears         622.282925
Weight         18.609651
dtype: float64

In [16]:
#t and p-Values
print(model.tvalues, '\n', model.pvalues)

Intercept    -5.323309
Age_08_04   -46.728942
KM          -16.542560
HP           10.842418
Doors        -0.242055
Gears         3.152234
Weight       22.446903
dtype: float64 
 Intercept     1.181900e-07
Age_08_04    4.387432e-290
KM            2.238900e-56
HP            2.231791e-26
Doors         8.087723e-01
Gears         1.653931e-03
Weight        7.856458e-96
dtype: float64


In [17]:
(model.rsquared,model.rsquared_adj)

(0.8628024511073656, 0.8622263942190831)

In [20]:
#New data for prediction
new_data=pd.DataFrame({'Age_08_04':28,'KM':41000,'HP':90,'Doors':3,'Gears':5,'Weight':1165},index=[1])

In [21]:
model.predict(new_data)

1    16087.227617
dtype: float64

# Using Linear Model

In [23]:
cars.head()

Price  Age_08_04     KM  HP  Doors  Cylinders  Gears  Weight
0  13500         23  46986  90      3          4      5    1165
1  13750         23  72937  90      3          4      5    1165
2  13950         24  41711  90      3          4      5    1165
3  14950         26  48000  90      3          4      5    1165
4  13750         30  38500  90      3          4      5    1170

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
x=cars.iloc[:,1:]
y=cars.iloc[:,0]

In [29]:
classifier = LinearRegression()
classifier.fit(x,y)

LinearRegression()

In [30]:
#Predict for X dataset
y_pred = classifier.predict(x)
y_pred

array([16578.75559043, 16059.89549639, 16561.9808689 , ...,
        8405.49623612,  8529.73783775, 10637.87886606])

In [31]:
classifier.intercept_

-6984.373565913342

In [32]:
classifier.coef_

array([-1.22242218e+02, -1.99938382e-02,  2.83501494e+01, -9.68022942e+00,
        3.41060513e-13,  6.22282925e+02,  1.86096509e+01])

In [33]:
classifier.score(x,y)

0.8628024511073658

In [43]:
#new data for prediction
new_data=pd.DataFrame({'Age_08_04':28,'KM':41000,'HP':90,'Doors':3,'Cylinders':4,'Gears':5,'Weight':1165},index=[1])

In [42]:
classifier.predict(new_data)

array([16087.22761654])